### ISSUE TITLE
Can i use <RightDrag> and <RightRelease> map to gesture?

### ISSUE THREAD

**Issue by xaljer** [notomo/gesture.nvim#34]

**Comment by notomo** [comment]
Yes. But you need to disable `<RightMouse>`.
Otherwise, `<RightMouse>` mapping is fired on the first.

```vim
nnoremap <silent> <RightMouse> <Nop>
nnoremap <silent> <RightDrag> <Cmd>Gesture draw<CR>
nnoremap <silent> <RightRelease> <Cmd>Gesture finish<CR>
```

📝 `:help <RightMouse>`

**Comment by xaljer** [comment]
@notomo Thanks.

**Comment by notomo** [comment]
added to readme https://github.com/notomo/gesture.nvim/commit/4e7198ba1152ba1170a681155a51afa4dc113e41
