### ISSUE TITLE
[Feature Request] use this plugin to draw

### ISSUE THREAD

**Issue by cbochs** [notomo/gesture.nvim#37]
Hi! This is an awesome plugin. I have a slightly different use-case in mind than mapping gestures to actions. I would love to be able to use gesture.nvim as a drawing board. There appear to be only a few drawbacks right now:

1. I don't know if there's a good way to disable the floating window that presents your gestures in the middle of the screen
2. When you "stop" drawing, move your mouse elsewhere, and "start" drawing, the lines attempt to "re-connect" with each other. As a drawing board, it would be nice if these lines remained detached

Thanks!

**Comment by notomo** [comment]
That's an interesting request.
I created prototype in https://github.com/notomo/gesture.nvim/pull/38 .
Please try it and give me feedback!

**Comment by cbochs** [comment]
This is fantastic. Exactly what I was thinking.

One nit: using `<2-LeftMouse>` to finish drawing leaves the user in VISUAL mode, meaning they have to escape before continuing on. This is not a bit deal, just something I noticed.

Also, is this the point where I start asking for gesture.nvim to be converted into a full-blown drawing plugin? Draw shapes, select colours, save drawings, etc. 😉 (jk, but a fun idea)

Thank you!

**Comment by notomo** [comment]
Thanks!

> <2-LeftMouse> to finish drawing leaves the user in VISUAL mode

Indeed. (but user can select other keys)

> Also, is this the point where I start asking for gesture.nvim to be converted into a full-blown drawing plugin? Draw shapes, select colours, save drawings, etc. 😉 (jk, but a fun idea)

😆
