### ISSUE TITLE
[Feature Request] Improve double-click detection 

### ISSUE THREAD

**Issue by beelzebielsk** [notomo/gesture.nvim#39]
Vim/Neovim's double-click detection is frustrating. Sometimes it will miss a double-click because my finger moved slightly. I use vim often on a touchscreen device, so it's a problem for me.

Could you improve double-click detection? Do you consider that within scope of your plugin? I was thinking you could consider it a gesture. If not, let me know and I'll either make my own plugin or open an issue with neovim.

I believe the problem is both clicks have to happen in the same cell on screen. Some concrete ideas I have for improving detection:

- Track clicks, when they happen and their locations. This may be possible by mapping LeftMouse to some click logger in gesture.nvim.
- If a series of clicks, starting from the latest click, meet some criteria for being close enough and fast enough, send out a double-click. Some example criteria are clicks happen within a 3x3 box, and within some short window of time. The click could be dispatched to the midpoint of the clicks.

**Comment by beelzebielsk** [comment]
This can be extended for triple and quadruple clicks, too.

**Comment by notomo** [comment]
Thanks interesting request!

But, I think the feature should be implement by other plugin.
Even if implemented in a way that fits the current interface, the accuracy may not be satisfactory.

📝 didn't work experimental code.

```lua
local gesture = require("gesture")

vim.keymap.set("n", "<LeftMouse>", function()
  gesture.draw({ length_thresholds = { x = 0, y = 0 } })
  gesture.suspend()
end, { silent = true })

gesture.register({
  name = "test",
  inputs = { gesture.up({ max_length = 3 }), gesture.up({ max_length = 3 }) },
  action = function()
    print("test")
  end,
  nowait = true,
})
```

```diff
diff --git a/lua/gesture/core/point.lua b/lua/gesture/core/point.lua
index 01e83e1..8aa4abd 100644
--- a/lua/gesture/core/point.lua
+++ b/lua/gesture/core/point.lua
@@ -21,7 +21,7 @@ function Point.line_to(self, point)
   if length_x > length_y then
     direction = diff_x > 0 and RIGHT or LEFT
     length = length_x
-  elseif length_y >= length_x and length_y > 0 then
+  elseif length_y >= length_x then
     direction = diff_y > 0 and DOWN or UP
     length = length_y
   else
```
