### ISSUE TITLE
Question: Is your plugin tested on Window OS?

### ISSUE THREAD

**Issue by hungnguyen1503** [notomo/gesture.nvim#42]
I have a problem with the mouse drawing. It seems to be delayed in the start time draw when I draw on Windows OS. When I tried it on Linux OS, It worked very well and didn't have a time delay when I drew.
Could you please help me to check it?
Many thanks 🍡

**Comment by notomo** [comment]
Hi!

I'm using Windows (mainly WSL).
I have no performance problems on WSL.

I have tested just now on Windows (not WSL).
But I confirmed the performance like WSL.

Hmm. I have no idea.
If you setup plugin lazy loading, the first drawing may delay.

📝 Windows tested version info

- nvim v0.10.0-dev-2295+g672556525
- GUI case
    - neovim-qt v0.2.18
- Terminal case
    - windows terminal

**Comment by hungnguyen1503** [comment]
I see, my config has worked without delay after removing lazy loading.
This ticket can be closed. 🔐 
Thanks for your help. 🚀
